export type IconName =
'3DRotationLine' |
'5CirclesGroupSuppliesFill' |
'5CirclesGroupSuppliesLine' |
'AddDocumentFill' |
'AddDocumentLine' |
'AddNoteFill' |
'AddNoteLine' |
'AddToClipboardFill' |
'AddToClipboardLine' |
'AirfareFill' |
'AirfareLine' |
'AirMattressFill' |
'AirMattressLine' |
'AirplaneModeFlightAirportFill' |
'AirplaneModeFlightAirportLine' |
'AirplaneModeOffFill' |
'AirplaneModeOffLine' |
'AirplayFill' |
'AirplayLine' |
'AlarmAddFill' |
'AlarmAddLine' |
'AlarmOffFill' |
'AlarmOffLine' |
'AlarmOnFill' |
'AlarmOnLine' |
'AlarmSnoozeFill' |
'AlarmSnoozeLine' |
'AlertAddFill' |
'AlertAddLine' |
'AlertErrorFill' |
'AlertErrorLine' |
'ALetterLine' |
'AlighHorizontalCenterLine' |
'AlighVerticalCenterLine' |
'AlignBottomLine' |
'AlignLeftLine' |
'AlignRightLine' |
'AlignTopLine' |
'AllInboxesFill' |
'AllInboxesLine' |
'AllInclusiveInfinityLine' |
'AllOutFill' |
'AllOutLine' |
'AmericanFootballBallFill' |
'AmericanFootballBallLine' |
'AmericanFootballHelmetFill' |
'AmericanFootballHelmetLine' |
'AngryOnyxFill' |
'AngryOnyxLine' |
'ApplicationFill' |
'ApplicationLine' |
'ApplicationsAppsFill' |
'ApplicationsAppsLine' |
'ApplicationSettingsOptionsFill' |
'ApplicationSettingsOptionsLine' |
'ArchiveFill' |
'ArchiveLine' |
'ArchivesFill' |
'ArchivesLine' |
'ArrowDownLine' |
'ArrowInCircleDownFill' |
'ArrowInCircleDownLine' |
'ArrowInCircleLeftDownFill' |
'ArrowInCircleLeftDownLine' |
'ArrowInCircleLeftFill' |
'ArrowInCircleLeftLine' |
'ArrowInCircleLeftUpFill' |
'ArrowInCircleLeftUpLine' |
'ArrowInCircleRightDownFill' |
'ArrowInCircleRightDownLine' |
'ArrowInCircleRightFill' |
'ArrowInCircleRightLine' |
'ArrowInCircleRightUpFill' |
'ArrowInCircleRightUpLine' |
'ArrowInCircleUpFill' |
'ArrowInCircleUpLine' |
'ArrowLeftDownLine' |
'ArrowLeftLine' |
'ArrowLeftUpLine' |
'ArrowRightDownLine' |
'ArrowRightForwardLine' |
'ArrowRightUpOpenInNewLine' |
'ArrowThinDownLine' |
'ArrowThinLeftBackspaceLine' |
'ArrowThinLeftDownLine' |
'ArrowThinLeftUpLine' |
'ArrowThinRightDownLine' |
'ArrowThinRightLine' |
'ArrowThinRightUpLine' |
'ArrowThinUpLine' |
'ArrowUpLine' |
'ArtTrackFill' |
'ArtTrackLine' |
'AspectRatioFill' |
'AspectRatioLine' |
'AssignmentFill' |
'AssignmentLateFill' |
'AssignmentLateLine' |
'AssignmentLine' |
'AssignmentOnFill' |
'AssignmentOnLine' |
'AssignmentReturnedFill' |
'AssignmentReturnedLine' |
'AssignmentReturnFill' |
'AssignmentReturnLine' |
'AtheismLine' |
'AtmAutomatedTellerMachineFill' |
'AtmAutomatedTellerMachineLine' |
'AtmCardFill' |
'AtmCardLine' |
'AtmCashDepositFill' |
'AtmCashDepositLine' |
'AtmCashFill' |
'AtmCashLine' |
'AtmCashWithdrawalFill' |
'AtmCashWithdrawalLine' |
'BabyCarriageBuggyStrollerChildFriendlyFill' |
'BabyCarriageBuggyStrollerChildFriendlyLine' |
'BackspaceAltFill' |
'BackspaceAltLine' |
'BackupRestoreLine' |
'BagBaggageLuggageFill' |
'BagBaggageLuggageLine' |
'BaggageClaimFill' |
'BaggageClaimLine' |
'BankAccountFill' |
'BankAccountLine' |
'BankBuildingUsdFill' |
'BankBuildingUsdLine' |
'BankCardCreditDebitFill' |
'BankCardCreditDebitLine' |
'BarbershopHaircutHairdressingSalonLine' |
'BarChairFill' |
'BarChairLine' |
'BasketballBallFill' |
'BasketballBallLine' |
'Battery0EmptyLine' |
'Battery100FullFill' |
'Battery100FullLine' |
'Battery25Fill' |
'Battery25Line' |
'Battery50Fill' |
'Battery50Line' |
'Battery75Fill' |
'Battery75Line' |
'BatteryAlertFill' |
'BatteryAlertLine' |
'BatteryCharging0EmptyFill' |
'BatteryCharging0EmptyLine' |
'BatteryCharging100FullFill' |
'BatteryCharging100FullLine' |
'BatteryCharging25Fill' |
'BatteryCharging25Line' |
'BatteryCharging50Fill' |
'BatteryCharging50Line' |
'BatteryCharging75Fill' |
'BatteryCharging75Line' |
'BatteryChargingFill' |
'BatteryChargingLine' |
'BatteryFill' |
'BatteryLine' |
'BatteryUnknownFill' |
'BatteryUnknownLine' |
'BeachVacationUmbrellaFill' |
'BeachVacationUmbrellaLine' |
'BicycleLine' |
'BLetterLine' |
'BlockNotInterestedProhibitedFill' |
'BlockNotInterestedProhibitedLine' |
'BluetoothAudioLine' |
'BluetoothLine' |
'BluetoothOffLine' |
'BluetoothOnLine' |
'BluetoothSettingsLine' |
'BluetoothSignalLine' |
'BookCoverFill' |
'BookCoverLine' |
'BookmarkFill' |
'BookmarkLine' |
'BorderAllLine' |
'BorderBottomLine' |
'BorderCenterHorizontalLine' |
'BorderCenterVerticalLine' |
'BorderClearLine' |
'BorderInnerLine' |
'BorderLeftLine' |
'BorderOuterLine' |
'BorderRightLine' |
'BorderStyleLine' |
'BorderTopLine' |
'BoxAddFill' |
'BoxAddLine' |
'BoxCloseFill' |
'BoxCloseLine' |
'BoxDeleteFill' |
'BoxDeleteLine' |
'BoxingGloveBoxFill' |
'BoxingGloveBoxLine' |
'BrandingWatermarkFill' |
'BrandingWatermarkLine' |
'BrightnessLowFill' |
'BrightnessLowLine' |
'BrightnessMediumFill' |
'BrightnessMediumLine' |
'BrigtnessAutoLine' |
'BroadcastTvFill' |
'BroadcastTvLine' |
'BrowserIeInternetExplorerFirefoxSafariOperaFill' |
'BrowserIeInternetExplorerFirefoxSafariOperaLine' |
'BuddhismLine' |
'BugReportFill' |
'BugReportLine' |
'BunkBedFill' |
'BunkBedLine' |
'ButtonFill' |
'ButtonLine' |
'ButtonWithTextFill' |
'ButtonWithTextLine' |
'CakeBirthdayFill' |
'CakeBirthdayLine' |
'CalendarFill' |
'CalendarLine' |
'CallMissedLine' |
'CallMissedOutgoingLine' |
'CallToActionCtaButtonFill' |
'CallToActionCtaButtonLine' |
'CameraDsrlLocalSeePhotoShootFill' |
'CameraDsrlLocalSeePhotoShootLine' |
'CamerasPhotoFearPartyModeFill' |
'CamerasPhotoFearPartyModeLine' |
'CameraVideoMovieFill' |
'CameraVideoMovieLine' |
'CameraVideoOffFill' |
'CameraVideoOffLine' |
'CancelClearCloseCircleDeleteTextHighlightOffFill' |
'CancelClearCloseCircleDeleteTextHighlightOffLine' |
'CanFill' |
'CanLine' |
'CapslockLine' |
'CapsuleHotelFill' |
'CapsuleHotelLine' |
'CartonBoxCardboardFill' |
'CartonBoxCardboardLine' |
'CashMoneyFill' |
'CashMoneyLine' |
'CastConnectedFill' |
'CastConnectedLine' |
'CastDisabledFill' |
'CastDisabledLine' |
'CellPhoneFlipFill' |
'CellPhoneFlipLine' |
'CellPhoneSliderFill' |
'CellPhoneSliderLine' |
'CellPhoneWithKeyboardOldPhoneFill' |
'CellPhoneWithKeyboardOldPhoneLine' |
'CellPhoneWithQwertyKeyboardFill' |
'CellPhoneWithQwertyKeyboardLine' |
'CelularOffLine' |
'ChairClassicFill' |
'ChairClassicLine' |
'ChairModernCrossStrutsFill' |
'ChairModernCrossStrutsLine' |
'ChairModernFill' |
'ChairModernLine' |
'CharityDonationsFill' |
'CharityDonationsLine' |
'ChartAssessmentFill' |
'ChartAssessmentLine' |
'ChartBarInvestmentEqualizerGraphicEqLine' |
'ChartBubbleFill' |
'ChartBubbleLine' |
'ChartLineInvestmentLine' |
'ChartMultipleFill' |
'ChartMultipleLine' |
'ChartPieDataUsageCircularDiagramFill' |
'ChartPieDataUsageCircularDiagramLine' |
'ChatQuestionAnswerFill' |
'ChatQuestionAnswerLine' |
'CheckAllDoneAllDoubleCheckTickAllLine' |
'CheckboxCheckedFill' |
'CheckboxCheckedLine' |
'CheckBoxIndeterminateFill' |
'CheckBoxIndeterminateLine' |
'CheckboxUncheckedFill' |
'CheckboxUncheckedLine' |
'CheckCheckingFill' |
'CheckCheckingLine' |
'CheckedCheckCircleFill' |
'CheckedCheckCircleLine' |
'CheckmarkDoneCheckTickLine' |
'ChevronDownKeyboardArrowDownLine' |
'ChevronInCircleDownDropDownFill' |
'ChevronInCircleDownDropDownLine' |
'ChevronInCircleLeftDownFill' |
'ChevronInCircleLeftDownLine' |
'ChevronInCircleLeftFill' |
'ChevronInCircleLeftLine' |
'ChevronInCircleLeftUpFill' |
'ChevronInCircleLeftUpLine' |
'ChevronInCircleRightDownFill' |
'ChevronInCircleRightDownLine' |
'ChevronInCircleRightFill' |
'ChevronInCircleRightLine' |
'ChevronInCircleRightUpFill' |
'ChevronInCircleRightUpLine' |
'ChevronInCircleUpFill' |
'ChevronInCircleUpLine' |
'ChevronLeftDownLine' |
'ChevronLeftKeyboardArrowLeftLine' |
'ChevronLeftUpLine' |
'ChevronRightDownLine' |
'ChevronRightKeyboardArrowRightLine' |
'ChevronRightUpLine' |
'ChevronSmallDownDropDownExpandMoreLine' |
'ChevronSmallLeftDownLine' |
'ChevronSmallLeftLine' |
'ChevronSmallLeftUpLine' |
'ChevronSmallRightDownLine' |
'ChevronSmallRightLine' |
'ChevronSmallRightUpLine' |
'ChevronSmallUpExpandLessLine' |
'ChevronUpKeyboardArrowUpLine' |
'ChristianityFill' |
'ChristianityLine' |
'CircleFullMoonLine' |
'CircleMoonFullFill' |
'CityFill' |
'CityLine' |
'CLetterLine' |
'ClipboardPasteFill' |
'ClipboardPasteLine' |
'ClockAlarmFill' |
'ClockAlarmLine' |
'ClockTimeWatchLaterFill' |
'ClockTimeWatchLaterLine' |
'CloseAllClearLine' |
'ClosedCaptionFill' |
'ClosedCaptionLine' |
'CloseDeleteCrossClearLine' |
'CloudCloudyFill' |
'CloudCloudyLine' |
'CloudDownloadBackupFill' |
'CloudDownloadBackupLine' |
'CloudOffFill' |
'CloudOffLine' |
'CloudQueueFill' |
'CloudQueueLine' |
'CloudSyncedFill' |
'CloudSyncedLine' |
'CloudSyncFill' |
'CloudSyncLine' |
'CloudUploadFill' |
'CloudUploadLine' |
'CocktailBarDrinkFill' |
'CocktailBarDrinkLine' |
'CodeLine' |
'CollegeSchoolEducationFill' |
'CollegeSchoolEducationLine' |
'CompactCameraFill' |
'CompactCameraLine' |
'CompassExploreFill' |
'CompassExploreLine' |
'ComputerTableFill' |
'ComputerTableLine' |
'ConfirmationNumberFill' |
'ConfirmationNumberLine' |
'ControllerRemoteWirelessFill' |
'ControllerRemoteWirelessLine' |
'ControlPointDuplicateFill' |
'ControlPointDuplicateLine' |
'CoordinatesGpsLocationNotFixedLine' |
'CoordinatesOffLocationOffGpsOffLine' |
'CopyFill' |
'CopyLine' |
'CopyrightFill' |
'CopyrightLine' |
'CosmeticsFill' |
'CosmeticsLine' |
'CouchSofaWeekendFill' |
'CouchSofaWeekendLine' |
'CourseCoursesFill' |
'CourseCoursesLine' |
'CreateNewFolderFill' |
'CreateNewFolderLine' |
'CreditCardFill' |
'CreditCardLine' |
'CribFill' |
'CribLine' |
'CricketFill' |
'CricketLine' |
'Crop16X9Fill' |
'Crop16X9Line' |
'Crop3X2Fill' |
'Crop3X2Line' |
'Crop5X4Fill' |
'Crop5X4Line' |
'Crop7X5Fill' |
'Crop7X5Line' |
'CropAndRotateLine' |
'CropFreeFill' |
'CropFreeLine' |
'CropVerticalFill' |
'CropVerticalLine' |
'CupCoffeeTeaCafeCaffeeTeahouseFill' |
'CupCoffeeTeaCafeCaffeeTeahouseLine' |
'CupPrizeCompetitionsFill' |
'CupPrizeCompetitionsLine' |
'DashboardViewDashboardFill' |
'DashboardViewDashboardLine' |
'DateRangeFill' |
'DateRangeLine' |
'DebitCardFill' |
'DebitCardLine' |
'DecagonFill' |
'DecagonLine' |
'DeleteForeverFill' |
'DeleteForeverLine' |
'DeleteSweepFill' |
'DeleteSweepLine' |
'DesktopMacFill' |
'DesktopMacLine' |
'DesktopWindowsFill' |
'DesktopWindowsLine' |
'DeviceInformationFill' |
'DeviceInformationLine' |
'DeviceSettingsFill' |
'DeviceSettingsLine' |
'DiamondRedDiamondFill' |
'DiamondRedDiamondLine' |
'DiceCasinoFill' |
'DiceCasinoLine' |
'DiningFill' |
'DiningLine' |
'DiskAlertFullFill' |
'DiskAlertFullLine' |
'DiskCompactCdFill' |
'DiskCompactCdLine' |
'DizzySentimentVeryDissatisfiedFill' |
'DizzySentimentVeryDissatisfiedLine' |
'DLetterLine' |
'DockStationFill' |
'DockStationLine' |
'DocumentBackupFill' |
'DocumentBackupLine' |
'DocumentDiagramPollFill' |
'DocumentDiagramPollLine' |
'DocumentNewEmptyFill' |
'DocumentNewEmptyLine' |
'DocumentTableFill' |
'DocumentTableLine' |
'DocumentTextDescriptionFill' |
'DocumentTextDescriptionLine' |
'DomainFill' |
'DomainLine' |
'DonutDiagramFill' |
'DonutDiagramLine' |
'DoubleBedBedroomFill' |
'DoubleBedBedroomLine' |
'DownloadGetAppLine' |
'DroolingFill' |
'DroolingLine' |
'DropHumidityFill' |
'DropHumidityLine' |
'DropPinLocationPlaceFill' |
'DropPinLocationPlaceLine' |
'DropWaterHumidityFill' |
'DropWaterHumidityLine' |
'EarthAmericaPlanetFill' |
'EarthAmericaPlanetLine' |
'EarthAustraliaPlanetFill' |
'EarthAustraliaPlanetLine' |
'EarthEurasiaAfricaPlanetFill' |
'EarthEurasiaAfricaPlanetLine' |
'EarthPlanetFill' |
'EarthPlanetLine' |
'EasternChristianityFill' |
'EasternChristianityLine' |
'EjectCircleFill' |
'EjectCircleLine' |
'EjectFill' |
'EjectLine' |
'ELetterLine' |
'EnergyElectricityFill' |
'EnergyElectricityLine' |
'EnhancedEncryptionFill' |
'EnhancedEncryptionLine' |
'EnterEntranceExitToAppFill' |
'EnterEntranceExitToAppLine' |
'ESimEmbeddedMff2Fill' |
'ESimEmbeddedMff2Line' |
'EthernetLine' |
'EuroLine' |
'EvChargingStationFill' |
'EvChargingStationLine' |
'EventAvailableFill' |
'EventAvailableLine' |
'EventBusyFill' |
'EventBusyLine' |
'EventNoteFill' |
'EventNoteLine' |
'ExitFill' |
'ExitLine' |
'ExpensesOutcomePaymentFill' |
'ExpensesOutcomePaymentLine' |
'ExplicitContentFuckCuntShitFill' |
'ExplicitContentFuckCuntShitLine' |
'FaceChildChildCareBabysitterFill' |
'FaceChildChildCareBabysitterLine' |
'FastForwardCircleFill' |
'FastForwardCircleLine' |
'FastForwardFill' |
'FastForwardLine' |
'FastRewindCircleFill' |
'FastRewindCircleLine' |
'FastRewindFill' |
'FastRewindLine' |
'FeaturedPlaylistLine' |
'FeaturedVideoFill' |
'FeaturedVideoLine' |
'FiberDvrFill' |
'FiberDvrLine' |
'FiberSmartRecordFill' |
'FiberSmartRecordLine' |
'FilmRollMovieMoviesFill' |
'FilmRollMovieMoviesLine' |
'FindReplaceLine' |
'FireHotFill' |
'FireHotLine' |
'FirstLine' |
'FitnessCenterGymSportDumbbellFill' |
'FitnessCenterGymSportDumbbellLine' |
'FlagFill' |
'FlagLine' |
'FLetterLine' |
'FlipToBackFill' |
'FlipToBackLine' |
'FlipToFrontFill' |
'FlipToFrontLine' |
'FloorMattressFill' |
'FloorMattressLine' |
'FloppyDiskSaveDisketteDiskFill' |
'FloppyDiskSaveDisketteDiskLine' |
'FogHazeLine' |
'FolderFavoriteFill' |
'FolderFavoriteLine' |
'FolderFill' |
'FolderLine' |
'FolderMediaFill' |
'FolderMediaLine' |
'FolderOpenedFill' |
'FolderOpenedLine' |
'FolderPersonalFill' |
'FolderPersonalLine' |
'FolderSharedFill' |
'FolderSharedLine' |
'FoldLine' |
'FontFileDownloadFill' |
'FontFileDownloadLine' |
'FontFileFill' |
'FontFileLine' |
'FoodDiningRestaurantFill' |
'FoodDiningRestaurantLine' |
'FootballBallSoccerBallFill' |
'FootballBallSoccerBallLine' |
'FreehandGestureLine' |
'FridgeFill' |
'FridgeLine' |
'FrowningDissatisfiedSentimentVeryDissatisfiedFill' |
'FrowningDissatisfiedSentimentVeryDissatisfiedLine' |
'FrowningMoodBadFill' |
'FrowningMoodBadLine' |
'FullscreenExitLine' |
'FullscreenLine' |
'GamepadJoystickControllerFill' |
'GamepadJoystickControllerLine' |
'GamepadWireJoystickControllerFill' |
'GamepadWireJoystickControllerLine' |
'GamepadWirelessJoystickControllerFill' |
'GamepadWirelessJoystickControllerLine' |
'GamesFill' |
'GamesLine' |
'GasStationFill' |
'GasStationLine' |
'GearSettingsMaintenanceFill' |
'GearSettingsMaintenanceLine' |
'GifGraphicsInterchangeFormatFill' |
'GifGraphicsInterchangeFormatLine' |
'GiftCardRedeemFill' |
'GiftCardRedeemLine' |
'GiftPresentCharityFill' |
'GiftPresentCharityLine' |
'GlassOfSparklingWaterFill' |
'GlassOfSparklingWaterLine' |
'GlassOfWaterDrinkHydrationFill' |
'GlassOfWaterDrinkHydrationLine' |
'GlassRecycledBottleFill' |
'GlassRecycledBottleLine' |
'GLetterLine' |
'GolfFill' |
'GolfLine' |
'GrimmingMoodGoodSentimentSatisfiedFill' |
'GrimmingMoodGoodSentimentSatisfiedLine' |
'GrinSentimentVerySatisfiedGrinningFaceWithSmilingEyesFill' |
'GrinSentimentVerySatisfiedGrinningFaceWithSmilingEyesLine' |
'GroupPeopleCommunityFill' |
'GroupPeopleCommunityLine' |
'HailHeavyFill' |
'HailHeavyLine' |
'HailLowFill' |
'HailLowLine' |
'HailMediumFill' |
'HailMediumLine' |
'HalfCircleLeftMoonLastQuarterFill' |
'HalfCircleLeftMoonLastQuarterLine' |
'HalfCircleRightMoonFirstQuarterFill' |
'HalfCircleRightMoonFirstQuarterLine' |
'HallwayFill' |
'HallwayLine' |
'HammockFill' |
'HammockLine' |
'HdHighDefinitionFill' |
'HdHighDefinitionLine' |
'HeadsetHeadphonesListenAudioAuditionFill' |
'HeadsetHeadphonesListenAudioAuditionLine' |
'HeadsetWithMicrophoneHeadphonesVoiceChatFill' |
'HeadsetWithMicrophoneHeadphonesVoiceChatLine' |
'HeartLikeLoveFavoriteDidaFill' |
'HeartLikeLoveFavoriteDidaLine' |
'HelpQuestionFaqFill' |
'HelpQuestionFaqLine' |
'HeptagonSeptagonFill' |
'HeptagonSeptagonLine' |
'HexagonFill' |
'HexagonLine' |
'HideKeyboardFill' |
'HideKeyboardLine' |
'HighPriorityLine' |
'HinduismLine' |
'HistoryClockFill' |
'HistoryClockLine' |
'HistoryLine' |
'HLetterLine' |
'HospitalRedCrossHealthDoctorFill' |
'HospitalRedCrossHealthDoctorLine' |
'HostelFill' |
'HostelLine' |
'HotelFill' |
'HotelLine' |
'HourglassFill' |
'HourglassFinishFill' |
'HourglassFinishLine' |
'HourglassLine' |
'HourglassStartFill' |
'HourglassStartLine' |
'HouseHomeHousingFill' |
'HouseHomeHousingLine' |
'HqHighQualityFill' |
'HqHighQualityLine' |
'HttpFill' |
'HttpLine' |
'IceCreamFill' |
'IceCreamLine' |
'IceHockeyFill' |
'IceHockeyLine' |
'ILetterLine' |
'InboxFill' |
'InboxLine' |
'IncomeFill' |
'IncomeLine' |
'IndentDecreaseLine' |
'IndentIncreaseLine' |
'InfoItalicMoreDetailsInformationAboutFill' |
'InfoItalicMoreDetailsInformationAboutLine' |
'InfoMonospacedMoreDetailsInformationAboutFill' |
'InfoMonospacedMoreDetailsInformationAboutLine' |
'InfoSansSerifMoreDetailsInformationAboutFill' |
'InfoSansSerifMoreDetailsInformationAboutLine' |
'InputFill' |
'InputLine' |
'InvertColorsFill' |
'InvertColorsLine' |
'IrregularFill' |
'IrregularLine' |
'IslamFill' |
'IslamLine' |
'JLetterLine' |
'JudaismLine' |
'KeyboardFill' |
'KeyboardLine' |
'KeyboardWireFill' |
'KeyboardWirelessFill' |
'KeyboardWirelessLine' |
'KeyboardWireLine' |
'KeyRentRentalsFill' |
'KeyRentRentalsLine' |
'KingSizeBedFill' |
'KingSizeBedLine' |
'KitchenFill' |
'KitchenLine' |
'KiteFill' |
'KiteLine' |
'KLetterLine' |
'LabelFill' |
'LabelLine' |
'LaptopComputerNotebookMacbookFill' |
'LaptopComputerNotebookMacbookLine' |
'LastLine' |
'LaundryFill' |
'LaundryLine' |
'LayersFill' |
'LayersLine' |
'LayersOffFill' |
'LayersOffLine' |
'LibraryAddFill' |
'LibraryAddLine' |
'LibraryBuildingFill' |
'LibraryBuildingLine' |
'LibraryFill' |
'LibraryLine' |
'LibraryListFill' |
'LibraryListLine' |
'LibraryMusicFill' |
'LibraryMusicLine' |
'LibraryVideoFill' |
'LibraryVideoLine' |
'LightningFlashElectricityFill' |
'LightningFlashElectricityLine' |
'LightningFlashFill' |
'LightningFlashLine' |
'LineSpacingLine' |
'LineStyleLine' |
'LineWeightLine' |
'LinkChainLine' |
'ListBulletedViewListLine' |
'ListPlaylistQueueLine' |
'LLetterLine' |
'LoanCashBorrowFill' |
'LoanCashBorrowLine' |
'LoanRentBorrowFill' |
'LoanRentBorrowLine' |
'LocationAddFill' |
'LocationAddLine' |
'LocationAlertFill' |
'LocationAlertLine' |
'LocationEditFill' |
'LocationEditLine' |
'LocationOffFill' |
'LocationOffLine' |
'LocationOnBeenhereFill' |
'LocationOnBeenhereLine' |
'LocationPlaceFill' |
'LocationPlaceLine' |
'LocationRemoveFill' |
'LocationRemoveLine' |
'LocationUserFill' |
'LocationUserLine' |
'LockEncryptionSecurityFill' |
'LockEncryptionSecurityLine' |
'LockOpenUnlockFill' |
'LockOpenUnlockLine' |
'LoopCachedSyncLine' |
'LowPriorityLine' |
'LoyaltyFill' |
'LoyaltyLine' |
'MailboxFill' |
'MailboxLine' |
'MailEnvelopeFill' |
'MailEnvelopeLine' |
'MailReadDraftFill' |
'MailReadDraftLine' |
'MapFill' |
'MapLine' |
'MedalPrizeCompetitionFill' |
'MedalPrizeCompetitionLine' |
'MedicalInsuranceHealthFill' |
'MedicalInsuranceHealthLine' |
'MembershipCardFill' |
'MembershipCardLine' |
'MenuFill' |
'MenuHamburgerLine' |
'MenuLine' |
'MergeLine' |
'MessageFailedFill' |
'MessageFailedLine' |
'MessageFill' |
'MessageLine' |
'MessageListSpeakerNotesFill' |
'MessageListSpeakerNotesLine' |
'MicrophoneConcertsSingFill' |
'MicrophoneConcertsSingLine' |
'MicrophoneOffAltVoiceOffFill' |
'MicrophoneOffAltVoiceOffLine' |
'MicrophoneOffVoiceOffFill' |
'MicrophoneOffVoiceOffLine' |
'MicrophoneVoiceSpeechDictationFill' |
'MicrophoneVoiceSpeechDictationLine' |
'MicroSdCardFill' |
'MicroSdCardLine' |
'MicroSimCardFill' |
'MicroSimCardLine' |
'MiniSdCardFill' |
'MiniSdCardLine' |
'MinusDeleteRemoveLine' |
'MinusInCircleDoNotDisturbOnRemoveFill' |
'MinusInCircleDoNotDisturbOnRemoveLine' |
'MistLine' |
'MLetterLine' |
'MmsFill' |
'MmsLine' |
'MoonWaningCrescentRedCrescentFill' |
'MoonWaningCrescentRedCrescentLine' |
'MoonWaningGibbousFill' |
'MoonWaningGibbousLine' |
'MoonWaxingCrescentFill' |
'MoonWaxingCrescentLine' |
'MoonWaxingGibbousFill' |
'MoonWaxingGibbousLine' |
'MoreInCircleUncategorizedFill' |
'MoreInCircleUncategorizedLine' |
'MoreLine' |
'MoreVerticalLine' |
'MortgageFill' |
'MortgageLine' |
'MouseClassicFill' |
'MouseClassicLine' |
'MouseFill' |
'MouseLine' |
'MouseWireFill' |
'MouseWirelessFill' |
'MouseWirelessLine' |
'MouseWireLine' |
'MoveToInboxFill' |
'MoveToInboxLine' |
'MusicVideoFill' |
'MusicVideoLine' |
'MyLocationCoordinatesLocationOnGpsFixedLine' |
'NanoSimCardFill' |
'NanoSimCardLine' |
'NavigationFill' |
'NavigationLine' |
'NearMeFill' |
'NearMeLine' |
'NetworkCellLockLine' |
'NetworkCellSignalCellular1Line' |
'NetworkCellSignalCellular2Line' |
'NetworkCellSignalCellular3Line' |
'NetworkCellSignalCellular4Line' |
'NetworkCheckLine' |
'NetworkSettingsMobileDataSettingsLine' |
'NeutralSentimentNeutralFill' |
'NeutralSentimentNeutralLine' |
'NewFill' |
'NewLine' |
'NewReleasesFill' |
'NewReleasesLine' |
'NirvanaFill' |
'NirvanaLine' |
'NLetterLine' |
'NoEncryptionFill' |
'NoEncryptionLine' |
'NoEnergyNoPowerNoBatteryFill' |
'NoEnergyNoPowerNoBatteryLine' |
'NoMessageSpeakerNotesOffFill' |
'NoMessageSpeakerNotesOffLine' |
'NoMouthFill' |
'NoMouthLine' |
'NonagonEnneagonFill' |
'NonagonEnneagonLine' |
'NoSimCardFill' |
'NoSimCardLine' |
'NoteEditFill' |
'NoteEditLine' |
'NoteFill' |
'NoteLine' |
'NotificationBellAlertFill' |
'NotificationBellAlertLine' |
'NotificationOffFill' |
'NotificationOffLine' |
'NotificationPausedFill' |
'NotificationPausedLine' |
'OctagonFill' |
'OctagonLine' |
'OfferTagPriceFill' |
'OfferTagPriceLine' |
'OfficeChairFill' |
'OfficeChairLine' |
'OldTvFill' |
'OldTvLine' |
'OLetterLine' |
'OnDemandTvFill' |
'OnDemandTvLine' |
'OnDemandVideoFill' |
'OnDemandVideoLine' |
'OpacityFill' |
'OpacityLine' |
'OpenInBrowserFill' |
'OpenInBrowserLine' |
'OpenInNewLaunchLine' |
'OpenWithLine' |
'OvalHorizontalFill' |
'OvalHorizontalLine' |
'OvalVerticalFill' |
'OvalVerticalLine' |
'OverscanFill' |
'OverscanLine' |
'PaperClipAttachmentLine' |
'ParallelogramFill' |
'ParallelogramLine' |
'PartlyCloudyFill' |
'PartlyCloudyLine' |
'PauseCircleFill' |
'PauseCircleLine' |
'PauseLine' |
'PawPetsAnimalsPetFill' |
'PawPetsAnimalsPetLine' |
'PencilEditCreateFill' |
'PencilEditCreateLine' |
'PentagonPentagramFill' |
'PentagonPentagramLine' |
'PermissionCameraMicrophoneFill' |
'PermissionCameraMicrophoneLine' |
'PersonalAssignmentFill' |
'PersonalAssignmentLine' |
'PersonalCalendarContactCalendarFill' |
'PersonalCalendarContactCalendarLine' |
'PharmacyDrugStoresFill' |
'PharmacyDrugStoresLine' |
'PhoneCallFill' |
'PhoneCallLine' |
'PhoneForwardedFill' |
'PhoneForwardedLine' |
'PhoneInTalkFill' |
'PhoneInTalkLine' |
'PhoneLockedFill' |
'PhoneLockedLine' |
'PhoneMessageFill' |
'PhoneMessageLine' |
'PhoneMissedFill' |
'PhoneMissedLine' |
'PhonePausedFill' |
'PhonePausedLine' |
'PhoneSettingsFill' |
'PhoneSettingsLine' |
'PhotoImageWallpaperFill' |
'PhotoImageWallpaperLine' |
'PictureDecorationFill' |
'PictureDecorationLine' |
'PictureInPictureAltFill' |
'PictureInPictureAltLine' |
'PictureInPictureFill' |
'PictureInPictureLine' |
'PinFill' |
'PinLine' |
'PinTextFill' |
'PinTextLine' |
'PizzaSliceFill' |
'PizzaSliceLine' |
'PlaceFavoriteFill' |
'PlaceFavoriteLine' |
'PlanetEarthInternetPublicFill' |
'PlanetEarthInternetPublicLine' |
'PlasticBottleRecyclingFill' |
'PlasticBottleRecyclingLine' |
'PlasticHdpeLine' |
'PlasticLdpeLine' |
'PlasticOtherLine' |
'PlasticPetLine' |
'PlasticPpLine' |
'PlasticPsLine' |
'PlasticPvcLine' |
'PlayCircleFill' |
'PlayCircleLine' |
'PlaylistAddAddToQueueLine' |
'PlaylistCheckLine' |
'PlaylistPlayQueueMusicLine' |
'PlaylistRemoveRemoveFromQueueLine' |
'PlayStartFill' |
'PlayStartLine' |
'PLetterParkingLine' |
'PlusAddCreateLine' |
'PlusInCircleAddCreateFill' |
'PlusInCircleAddCreateLine' |
'PointAndShootCameraFill' |
'PointAndShootCameraLine' |
'PoolBLine' |
'PotCookingFill' |
'PotCookingLine' |
'PowerConnecotForkFill' |
'PowerConnecotForkLine' |
'PowerInputLine' |
'PowerOnOffButtonLine' |
'PowerSettingsFill' |
'PowerSettingsLine' |
'PowerSocketALine' |
'PowerSocketBFill' |
'PowerSocketBLine' |
'PowerSocketCFill' |
'PowerSocketCLine' |
'PowerSocketDFill' |
'PowerSocketDLine' |
'PowerSocketEFill' |
'PowerSocketELine' |
'PowerSocketFFill' |
'PowerSocketFillill' |
'PowerSocketFLine' |
'PowerSocketGFill' |
'PowerSocketGLine' |
'PowerSocketHFill' |
'PowerSocketHLine' |
'PowerSocketIFill' |
'PowerSocketILine' |
'PowerSocketJFill' |
'PowerSocketJLine' |
'PowerSocketKFill' |
'PowerSocketKLine' |
'PowerSocketLFill' |
'PowerSocketLLine' |
'PowerSocketMFill' |
'PowerSocketMLine' |
'PowerSocketNFill' |
'PowerSocketNLine' |
'PowerSocketOFill' |
'PowerSocketOLine' |
'PrepaidCardFill' |
'PrepaidCardLine' |
'PrinterPrintPrintshopFill' |
'PrinterPrintPrintshopLine' |
'ProgramSoftwareFill' |
'ProgramSoftwareLine' |
'PublishLine' |
'PuzzleExtensionFill' |
'PuzzleExtensionLine' |
'QLetterLine' |
'QueenSizeBedFill' |
'QueenSizeBedLine' |
'RadioButtonOffFill' |
'RadioButtonOffLine' |
'RadioButtonOnFill' |
'RadioButtonOnLine' |
'RadioVintageStationRecieverFill' |
'RadioVintageStationRecieverLine' |
'RainHeavyFill' |
'RainHeavyLine' |
'RainLightFill' |
'RainLightLine' |
'RainMediumFill' |
'RainMediumLine' |
'RateReviewFill' |
'RateReviewLine' |
'RatingsStarsFill' |
'RatingsStarsLine' |
'ReaderModeFill' |
'ReaderModeLine' |
'RecyclingLine' |
'RedoLine' |
'ReorderLine' |
'RepeatLine' |
'ReplayLine' |
'ReplyAllLine' |
'ReplyLine' |
'ReportFill' |
'ReportLine' |
'RestoreLine' |
'ReturnLine' |
'RhombusFill' |
'RhombusLine' |
'RLetterLine' |
'RockingChairFill' |
'RockingChairLine' |
'RoomServiceFill' |
'RoomServiceLine' |
'RotateCcwLine' |
'RotateCwLine' |
'RoundedCornerLine' |
'RouteDirectionsFill' |
'RouteDirectionsLine' |
'RouterFill' |
'RouterLine' |
'RugbyBallFill' |
'RugbyBallLine' |
'RussianRoubleRurLine' |
'SatanismLine' |
'SavingsFill' |
'SavingsLine' |
'ScalesJudgeJusticeCourthouseFill' |
'ScalesJudgeJusticeCourthouseLine' |
'ScannerScanFill' |
'ScannerScanLine' |
'ScheduledVideoFill' |
'ScheduledVideoLine' |
'ScheduleFill' |
'ScheduleLine' |
'ScientologyFill' |
'ScientologyLine' |
'ScissorsCutLine' |
'ScreenLockLandscapeFill' |
'ScreenLockLandscapeLine' |
'ScreenLockPortraitFill' |
'ScreenLockPortraitLine' |
'ScreenLockRotationFill' |
'ScreenLockRotationLine' |
'ScreenRotationFill' |
'ScreenRotationLine' |
'SdCardFill' |
'SdCardLine' |
'SearchEditLine' |
'SearchHistorySearchedForLine' |
'SearchMagnifyingGlassHandLensLine' |
'SearchOffLine' |
'SearchOnLine' |
'SearchOnPageFill' |
'SearchOnPageLine' |
'SearchPersonUserLine' |
'SecurityOffFill' |
'SecurityOffLine' |
'SecurityOnSecuredVerifiedFill' |
'SecurityOnSecuredVerifiedLine' |
'SendFill' |
'SendLine' |
'ServerDnsServerFill' |
'ServerDnsServerLine' |
'ShareAppleFill' |
'ShareAppleLine' |
'ShareGoogleFill' |
'ShareGoogleLine' |
'ShareMicrosoftFill' |
'ShareMicrosoftLine' |
'ShieldSecurityInsuranceFill' |
'ShieldSecurityInsuranceLine' |
'ShoppingBagMallShopStoreFill' |
'ShoppingBagMallShopStoreLine' |
'ShoppingBasketFill' |
'ShoppingBasketLine' |
'ShoppingCartGroceryStoreFill' |
'ShoppingCartGroceryStoreLine' |
'ShowHeavyFill' |
'ShowHeavyLine' |
'ShowToAllFill' |
'ShowToAllLine' |
'ShuffleLine' |
'SignalCellularAlert1Line' |
'SignalCellularAlert2Line' |
'SignalCellularAlert3Line' |
'SignalCellularAlert4Line' |
'SignalWifiOffLine' |
'SimCardFill' |
'SimCardLine' |
'SingleBedFill' |
'SingleBedLine' |
'SkipCircleFill' |
'SkipCircleLine' |
'SkipNextFill' |
'SkipNextLine' |
'SkipPreviousCircleFill' |
'SkipPreviousCircleLine' |
'SkipPreviousFill' |
'SkipPreviousLine' |
'SleetFill' |
'SleetLine' |
'SLetterLine' |
'SlightlyFrowningSadSentimentDissatisfiedFill' |
'SlightlyFrowningSadSentimentDissatisfiedLine' |
'SlowMotionVideoFill' |
'SlowMotionVideoLine' |
'SmartbandActivityTrackerFill' |
'SmartbandActivityTrackerLine' |
'SmartphoneAndroidFill' |
'SmartphoneAndroidLine' |
'SmartphoneAppleIphoneFill' |
'SmartphoneAppleIphoneLine' |
'SmartphoneIphoneAndroidBezellessFill' |
'SmartphoneIphoneAndroidBezellessLine' |
'SmartphoneWithOneCameraFill' |
'SmartphoneWithOneCameraLine' |
'SmartphoneWithTwoCamerasFill' |
'SmartphoneWithTwoCamerasLine' |
'SmartwatchRoundFill' |
'SmartwatchRoundLine' |
'SmartwatchSquareFill' |
'SmartwatchSquareLine' |
'SmileFill' |
'SmileLine' |
'SmilingSmileFill' |
'SmilingSmileLine' |
'SmogLine' |
'SnowflakeSnowAcUnitAirConditionerLine' |
'SnowLightFill' |
'SnowLightLine' |
'SnowMediumFill' |
'SnowMediumLine' |
'SofaBedFill' |
'SofaBedLine' |
'SofaEventSeatFill' |
'SofaEventSeatLine' |
'SortByAlphabetAzLine' |
'SortHighToLowFilterListLine' |
'SortLowToHighFilterListLine' |
'SoundMessageFill' |
'SoundMessageLine' |
'SoundOffMuteFill' |
'SoundOffMuteLine' |
'SpaFill' |
'SpaLine' |
'SpeakerGroupSpeakersFill' |
'SpeakerGroupSpeakersLine' |
'SpeakerSoundDynamicFill' |
'SpeakerSoundDynamicLine' |
'SpellCheckLine' |
'SplitLine' |
'SquareQuadrilateralTetragonFill' |
'SquareQuadrilateralTetragonLine' |
'StarGradeRatingFavoriteFavouriteFill' |
'StarGradeRatingFavoriteFavouriteLine' |
'StationerySuppliesFill' |
'StationerySuppliesLine' |
'StoolFill' |
'StoolLine' |
'StopCircleFill' |
'StopCircleLine' |
'StopFill' |
'StopLine' |
'StorageServerFill' |
'StorageServerLine' |
'StoreFill' |
'StoreLine' |
'StoveFill' |
'StoveLine' |
'SubdirectoryArrowLeftLine' |
'SubdirectoryArrowRightLine' |
'SubscriptionsAddedLibraryFill' |
'SubscriptionsAddedLibraryLine' |
'SubtitlesFill' |
'SubtitlesLine' |
'SunBrightnessHighFill' |
'SunBrightnessHighLine' |
'SunriseFill' |
'SunriseLine' |
'SunsetFill' |
'SunsetLine' |
'SurroundSound3DSoundFill' |
'SurroundSound3DSoundLine' |
'SwapCallsLine' |
'SwapHorizontalLine' |
'SwapVerticalLine' |
'SyncAutorenewLine' |
'SyncDisabledLine' |
'SyncErrorLine' |
'SystemUpdateFill' |
'SystemUpdateLine' |
'TabButtonLine' |
'TableFill' |
'TableLine' |
'TableOfContentTocContentLine' |
'TabletAndroidFill' |
'TabletAndroidLine' |
'TabletAppleIpadFill' |
'TabletAppleIpadLine' |
'TableTennisPingPongFill' |
'TableTennisPingPongLine' |
'TabletIpadFill' |
'TabletIpadLine' |
'TabTabsFill' |
'TabTabsLine' |
'TaoismFill' |
'TaoismLine' |
'TennisFill' |
'TennisLine' |
'TerrainMountainsFill' |
'TerrainMountainsLine' |
'TetraPakFill' |
'TetraPakLine' |
'TextAlignCenterLine' |
'TextAlignLeftViewHeadlineListLine' |
'TextAlignRightLine' |
'TextClipLine' |
'TextFormatLine' |
'TextJustifyAllLinesLine' |
'TextJustifyCenterLine' |
'TextJustifyLeftLine' |
'TextJustifyRightLine' |
'TextMessageFill' |
'TextMessageLine' |
'TextOverflowLine' |
'TextWrapLine' |
'TheatersEntertainmentFill' |
'TheatersEntertainmentLine' |
'ThunderstormWithHailFill' |
'ThunderstormWithHailLine' |
'ThunderstormWithRainFill' |
'ThunderstormWithRainLine' |
'ThunderstormWithSnowFill' |
'ThunderstormWithSnowLine' |
'TicketActivityPlayFill' |
'TicketActivityPlayLine' |
'TimelineFill' |
'TimelineLine' |
'TimerClockFill' |
'TimerClockLine' |
'TimerLine' |
'TLetterLine' |
'TodayDateFill' |
'TodayDateLine' |
'ToddlerBedFill' |
'ToddlerBedLine' |
'ToysToyShopChildrensRoomFill' |
'ToysToyShopChildrensRoomLine' |
'TrackLine' |
'TrafficLightFill' |
'TrafficLightLine' |
'TransfersImportExportCompareLine' |
'TransformLine' |
'TranslateTranslationLine' |
'TrapezoidFill' |
'TrapezoidLine' |
'TrashFullFill' |
'TrashFullLine' |
'TrashGarbageDeleteRemoveBinFill' |
'TrashGarbageDeleteRemoveBinLine' |
'TrashPartlyFullFill' |
'TrashPartlyFullLine' |
'TravelCardFill' |
'TravelCardLine' |
'TrendingDownLine' |
'TrendingFlatLine' |
'TrendingUpLine' |
'TriangleTrigonFill' |
'TriangleTrigonLine' |
'TShirtRoundNeckClothingFill' |
'TShirtRoundNeckClothingLine' |
'TvTelevisionCableFill' |
'TvTelevisionCableLine' |
'ULetterLine' |
'UnarchiveFill' |
'UnarchiveLine' |
'UndoLine' |
'UnfoldLine' |
'UpdateRefreshLine' |
'UploadLine' |
'UpsideDownFill' |
'UpsideDownLine' |
'UsdDollarLine' |
'UserIdentityPersonPersonalFill' |
'UserIdentityPersonPersonalLine' |
'UtilitiesFill' |
'UtilitiesLine' |
'VectorImageFill' |
'VectorImageLine' |
'VibrationFill' |
'VibrationLine' |
'VideoCallFill' |
'VideoCallLine' |
'VideoFill' |
'VideoLabelFill' |
'VideoLabelLine' |
'VideoLine' |
'VideoMessageFill' |
'VideoMessageLine' |
'ViewArrayFill' |
'ViewArrayLine' |
'ViewCarouselFill' |
'ViewCarouselLine' |
'ViewColumnsViewWeekFill' |
'ViewColumnsViewWeekLine' |
'ViewDayFill' |
'ViewDayLine' |
'ViewGridFill' |
'ViewGridLine' |
'ViewModuleFill' |
'ViewModuleLine' |
'ViewQuiltFill' |
'ViewQuiltLine' |
'ViewStreamViewAgendaFill' |
'ViewStreamViewAgendaLine' |
'VinylAlbumFill' |
'VinylAlbumLine' |
'VLetterLine' |
'VoiceMessageFill' |
'VoiceMessageLine' |
'VoiceSettingsMicrophoneFill' |
'VoiceSettingsMicrophoneLine' |
'VolumeDownFill' |
'VolumeDownLine' |
'VolumeMuteFill' |
'VolumeMuteLine' |
'VolumeUpFill' |
'VolumeUpLine' |
'VpnFill' |
'VpnLine' |
'WalletFill' |
'WalletLine' |
'WarningReportInDiamondProblemFill' |
'WarningReportInDiamondProblemLine' |
'WarningReportProblemFill' |
'WarningReportProblemLine' |
'WatchAnalogFill' |
'WatchAnalogLine' |
'WaterBedFill' |
'WaterBedLine' |
'WidgetsFill' |
'WidgetsLine' |
'WifiAlertSignalWifi1Line' |
'WifiAlertSignalWifi2Line' |
'WifiAlertSignalWifi3Line' |
'WifiAlertSignalWifi4Line' |
'WifiLockLine' |
'WifiSignal1Line' |
'WifiSignal2Line' |
'WifiSignal3Line' |
'WifiSignal4Line' |
'WifiTetheringLine' |
'WindowMacosMacintoshFill' |
'WindowMacosMacintoshLine' |
'WindowWindowsFill' |
'WindowWindowsLine' |
'WindSpeedHignLine' |
'WindSpeedLowLine' |
'WindSpeedMediumLine' |
'WirelessNfcLine' |
'WLetterLine' |
'WorkBusinessCenterBagFill' |
'WorkBusinessCenterBagLine' |
'WorkspaceFill' |
'WorkspaceLine' |
'WorkTableFill' |
'WorkTableLine' |
'XLetterLine' |
'YLetterLine' |
'ZLetterLine' |
'ZoomInArrowsLine' |
'ZoomInLine' |
'ZoomOutArrowsLine' |
'ZoomOutLine';

export default IconName;
